# ========================================
# INDICATOR DEFINITIONS AND LABELS
# ========================================

# Define indicator labels (English)
indicator_labels <- data.frame(
  indicator_id = c(
    "anc1", "anc1_after20", "anc1_before20", "anc4", "anc4plus",
    "anc_net",
    "bcg", "bcg_female", "bcg_male", "bcg_stock",
    "breastfeeding",
    "deliv_csection", "deliv_partograph", "deliv_vaginal", "delivery",
    "deliveries_adol", "delivery_vita",
    "diabetes_new", "diarrhoea",
    "fp_15a24ans", "fp_25plus",
    "fully_immunized",
    "gbv_cases", "gbv_referred",
    "gnl_attendance",
    "hiv_tested", "hiv_treated",
    "hypertension_new",
    "ifa",
    "inst_deliv_adults", "inst_deliv_under20",
    "ipd", "IPT3",
    "kmc",
    "livebirth",
    "mal_diag_treat_ACT", "mal_fever_tested", "mal_positive",
    "mal_positive_micros", "mal_positive_micros_ma", "mal_treatment",
    "malaria_confirmed", "malaria_tested", "malaria_treated",
    "maternal_deaths",
    "measles1", "measles2",
    "neonatal_deaths",
    "new_fp",
    "opd",
    "penta1", "penta1_female", "penta1_male",
    "penta3", "penta3_female", "penta3_male",
    "pnc1", "pnc1_mother", "pnc1_newborn",
    "PW_recieved_LLIN",
    "rr1",
    "sam", "sam_admit",
    "sba",
    "stillbirth",
    "tb_confirmed", "tb_treated",
    "u5_deaths", "u5_nutprog",
    "U5_LLIN",
    "underweight_newborn",
    "vaccins_completes", "vaccins_completes_fem", "vaccins_completes_mal",
    "vitA", "vitaminA"
  ),
  indicator_name = c(
    "Antenatal care 1st visit",
    "ANC 1st visit ≥ 20wks",
    "ANC 1st visit <20wks",
    "Antenatal care 4th visit",
    "Antenatal care 4+ visits",
    "Pregnant women who received impregnated mosquito net",
    "BCG vaccine",
    "BCG vaccine - Females",
    "BCG vaccine - Males",
    "BCG stock rupture days",
    "Live institutional births with immediate breastfeeding",
    "Deliveries - caesarian section",
    "Deliveries monitored using a partograph",
    "Deliveries - vaginal",
    "Institutional delivery",
    "Institutional deliveries: Mothers age 15-19",
    "Deliveries with vitamin A dose",
    "Diabetes new cases",
    "Diarrhoea cases < 5 years",
    "Family planning users 15-24 years",
    "Family planning users 25+ years",
    "Fully immunized <1 year",
    "Gender based violence cases seen",
    "Gender based violence cases referred for treatment",
    "General Attendance",
    "HIV tests performed",
    "PLHIV on ART regularly followed",
    "Hypertension new cases",
    "Pregnant women receiving iron folate",
    "Institutional deliveries (20+ years)",
    "Institutional deliveries - adolescents",
    "Inpatient visit",
    "IPT3 (pregnant women)",
    "Live institutional births benefiting from Kangaroo method",
    "Live births",
    "Persons Clinically diagnosed with Malaria treated with ACT",
    "Persons presenting with fever and tested (RDT and microscopy)",
    "Persons tested positive for malaria (RDT and microscopy)",
    "Persons tested positive for malaria by RDT",
    "Persons tested positive for malaria by RDT",
    "Persons with Confirmed Uncomplicated Malaria treated with ACT",
    "Confirmed malaria cases",
    "Malaria tests performed",
    "Malaria cases treated",
    "Maternal deaths",
    "Measles vaccine 1",
    "Measles vaccine 2",
    "Neonatal deaths",
    "New family planning acceptors",
    "Outpatient visit",
    "Penta vaccine 1",
    "Penta vaccine 1 - Females",
    "Penta vaccine 1 - Males",
    "Penta vaccine 3",
    "Penta vaccine 3 - Females",
    "Penta vaccine 3 - Males",
    "Postnatal care 1",
    "Postnatal care 1 (mothers)",
    "Postnatal care 1 (newborns)",
    "PW who received LLIN",
    "Measles-Rubella vaccine 1",
    "Children <5 treated for SAM",
    "Children <5 admitted for SAM treatment",
    "Deliveries by Skilled Birth Attendants (SBA)",
    "Still births",
    "TB cases confirmed",
    "TB cases treated",
    "Under 5 deaths",
    "Children <5 in nutrition program",
    "Children <5 yrs who received LLIN",
    "Low birth weight newborns",
    "Fully vaccinated (0-11 months)",
    "Fully vaccinated Females (0-11 months)",
    "Fully vaccinated Males (0-11 months)",
    "Children 6-59 months receiving two doses vitamin A",
    "Vitamin A given"
  ),
  stringsAsFactors = FALSE
)

# Define indicator labels (French)
indicator_labels_fr <- data.frame(
  indicator_id = c(
    "anc1", "anc1_after20", "anc1_before20", "anc4", "anc4plus",
    "anc_net",
    "bcg", "bcg_female", "bcg_male", "bcg_stock",
    "breastfeeding",
    "deliv_csection", "deliv_partograph", "deliv_vaginal", "delivery",
    "deliveries_adol", "delivery_vita",
    "diabetes_new", "diarrhoea",
    "fp_15a24ans", "fp_25plus",
    "fully_immunized",
    "gbv_cases", "gbv_referred",
    "gnl_attendance",
    "hiv_tested", "hiv_treated",
    "hypertension_new",
    "ifa",
    "inst_deliv_adults", "inst_deliv_under20",
    "ipd", "IPT3",
    "kmc",
    "livebirth",
    "mal_diag_treat_ACT", "mal_fever_tested", "mal_positive",
    "mal_positive_micros", "mal_positive_micros_ma", "mal_treatment",
    "malaria_confirmed", "malaria_tested", "malaria_treated",
    "maternal_deaths",
    "measles1", "measles2",
    "neonatal_deaths",
    "new_fp",
    "opd",
    "penta1", "penta1_female", "penta1_male",
    "penta3", "penta3_female", "penta3_male",
    "pnc1", "pnc1_mother", "pnc1_newborn",
    "PW_recieved_LLIN",
    "rr1",
    "sam", "sam_admit",
    "sba",
    "stillbirth",
    "tb_confirmed", "tb_treated",
    "u5_deaths", "u5_nutprog",
    "U5_LLIN",
    "underweight_newborn",
    "vaccins_completes", "vaccins_completes_fem", "vaccins_completes_mal",
    "vitA", "vitaminA"
  ),
  indicator_name = c(
    "CPN 1",
    "CPN 1 (≥ 20 semaines)",
    "CPN 1 (<20 semaines)",
    "CPN 4",
    "CPN 4 (au moins)",
    "Femmes enceintes ayant reçu une moustiquaire impregnee",
    "Vaccin BCG",
    "Vaccin BCG- Femelles",
    "Vaccin BCG- Males",
    "BCG | Nombre de jours de rupture de stocks",
    "Naissances Vivantes Institutionnels Mises au sein immédiate",
    "Accouchements - césarienne",
    "Accouchements avec partogramme",
    "Accouchements - voie basse",
    "Accouchements institutionnels",
    "Accouchements institutionnels: Age des meres entre 15-19 ans",
    "Accouchees qui ont recu une dose de vitamine A",
    "Diabète nouveaux cas",
    "Cas de diarrhée < 5 ans",
    "Total de femmes utilisatrices de PF 15-24 ans",
    "Total de femmes utilisatrices de PF 25ans et plus",
    "Complètement vaccinés <1 an",
    "Cas de violence basée sur le genre",
    "Cas VBG référés pour traitement",
    "Consultations générales",
    "Tests VIH effectués",
    "PVVIH sous ARV suivis régulièrement",
    "Hypertension nouveaux cas",
    "Nombre de Femmes enceintes recevant du fer folate",
    "Accouchements institutionnels (20 ans et plus)",
    "Accouchements institutionnels- adolescents",
    "Visites Hospitalières",
    "IPT3 (femmes enceintes)",
    "Naissances Vivantes Institutionnels Beneficiaires de methode Kangourou",
    "Naissances vivantes",
    "Cas de paludisme traités par ACT",
    "Personnes avec fièvre testées (TDR et microscopie)",
    "Personnes testées positives au paludisme (TDR et microscopie)",
    "Personnes testées positives au paludisme par TDR",
    "Personnes testées positives au paludisme par TDR",
    "Cas de paludisme confirmé traités par ACT",
    "Cas de paludisme confirmés",
    "Tests de paludisme effectués",
    "Cas de paludisme traités",
    "Décès maternels",
    "Vaccin Rougeole 1",
    "Vaccin Rougeole 2",
    "Décès néonatals",
    "PF - Nouvelles Acceptatrices",
    "Visites Ambulatoires",
    "Vaccin Penta 1",
    "Vaccination Penta 1 — Filles",
    "Vaccination Penta 1 — Garçons",
    "Vaccin Penta 3",
    "Vaccination Penta 3 — Filles",
    "Vaccination Penta 3 — Garçons",
    "Soins Postnatals 1",
    "Soins Postnatals 1- Mères",
    "Soins Postnatals 1- Nouveau-né",
    "Femmes enceintes ayant reçu MILD",
    "Vaccin Rougeole-Rubéole 1",
    "Enfants <5 ans traités pour MAS",
    "Enfants <5 ans admis pour traitement MAS",
    "Accouchements - Personnel Qualifié",
    "Mortinaissances",
    "Cas de tuberculose confirmés",
    "Cas de tuberculose traités",
    "Décès < 5 ans",
    "Enfants <5 dans le programme nutrition",
    "Enfants <5 ans ayant reçu MILD",
    "Naissances vivantes faible poids",
    "Total Complètement Vaccinees (0-11)",
    "Total Complètement Vaccinees Femelles (0-11 m)",
    "Total Complètement Vaccinees Males (0-11 m)",
    "Nombre d'enfants de 6 mois a 59 mois ayant recu deux doses",
    "Vitamine A administrée"
  ),
  stringsAsFactors = FALSE
)

# Define all category levels (ordered from most disrupted to most surplus)
all_categories <- c(
  "Disruption >20%", "Disruption 15-20%", "Disruption 10-15%",
  "Disruption 7-10%", "Disruption 5-7%", "Disruption 3-5%",
  "Stable",
  "Surplus 3-5%", "Surplus 5-7%", "Surplus 7-10%",
  "Surplus 10-15%", "Surplus 15-20%", "Surplus >20%",
  "Insufficient data"
)

# Define color palette for disruption categories
# Gradient: DARK RED → RED → YELLOW → GREEN → DARK GREEN
category_colors <- c(
  "Disruption >20%" = "#67001f",    # Very dark red (severe disruption)
  "Disruption 15-20%" = "#b2182b",  # Dark red
  "Disruption 10-15%" = "#d6604d",  # Medium-dark red
  "Disruption 7-10%" = "#f4a582",   # Medium red
  "Disruption 5-7%" = "#fddbc7",    # Light-medium red
  "Disruption 3-5%" = "#fee5d9",    # Light red
  "Stable" = "#ffffcc",             # Light yellow (stable ±3%)
  "Surplus 3-5%" = "#e5f5e0",       # Light green
  "Surplus 5-7%" = "#c7e9c0",       # Light-medium green
  "Surplus 7-10%" = "#a1d99b",      # Medium green
  "Surplus 10-15%" = "#74c476",     # Medium-dark green
  "Surplus 15-20%" = "#41ab5d",     # Dark green
  "Surplus >20%" = "#006d2c",       # Very dark green (strong surplus)
  "Insufficient data" = "#999999"   # Gray
)

# Simplified heatmap categories (aggregated bands)
heatmap_categories <- c(
  "Disruption >10%",
  "Disruption 5-10%",
  "Stable",
  "Surplus 5-10%",
  "Surplus >10%",
  "Insufficient data"
)

# Color palette aligned with simplified heatmap categories
heatmap_colors <- c(
  "Disruption >10%" = "#d7191c",
  "Disruption 5-10%" = "#fdae61",
  "Stable" = "#ffffcc",
  "Surplus 5-10%" = "#a6d96a",
  "Surplus >10%" = "#1a9641",
  "Insufficient data" = "#f0f0f0"
)
